# H2

spring.h2.console:
  enabled: true
  path: /h2

spring.datasource:
  url: jdbc:h2:~/putin_db
  username: sa
  password:
  driver-class-name: org.h2.Driver


spring.jpa.hibernate.ddl-auto: update